image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  #
  PUBLIC_REGISTRY_PROJECT_ID: 32304092

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging

ruff:
  script:
    - pip install ruff
    - ruff --output-format=gitlab --output-file gl-code-quality-report.json pyrmaid_celery
  artifacts:
    reports:
      codequality: gl-code-quality-report.json

# test:
#   script:
#     - pip install .
#     - flake8 --exit-zero --format gl-codeclimate --output-file examples-report.json --tee examples/
#     - python -m json.tool < examples-report.json

deploy:
  script:
    - env
    - pip install twine
    - python setup.py bdist_wheel
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*

deploy_public:
  script:
    - env
    - pip install twine
    - python setup.py bdist_wheel
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${PUBLIC_REGISTRY_PROJECT_ID}/packages/pypi dist/*
